display:
  default:
    display_title: Principale
    display_options:
      exposed_form:
        options:
          submit_button: Applica
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_desc_label: Disc
      pager:
        options:
          expose:
            items_per_page_label: 'Voci per pagina'
            items_per_page_options_all_label: '- Tutto -'
            offset_label: Scostamento
      fields:
        uid:
          label: 'Creato da'
        created:
          label: 'Creato il'
        parent_id:
          label: Genitore
        status:
          label: Pubblicato
        type:
          label: Tipo
        nothing:
          label: Azione
          alter:
            text: elimina
            alt: elimina
      filters:
        type:
          expose:
            label: Tipo
