label: 'Contenuti recenti'
description: 'Contenuti recenti.'
display:
  default:
    display_title: Principale
    display_options:
      exposed_form:
        options:
          submit_button: Applica
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_desc_label: Disc
      title: 'Contenuti recenti'
      empty:
        area_text_custom:
          content: 'Nessun contenuto disponibile.'
      use_more_text: Altro
  block_1:
    display_title: Blocco
