display:
  default:
    display_title: Principale
    display_options:
      exposed_form:
        options:
          submit_button: Applica
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_desc_label: Disc
      fields:
        title:
          label: Titolo
        unit_price__number:
          label: 'Prezzo unitario'
        quantity:
          label: Quantità
        total_price__number:
          label: 'Prezzo totale'
      arguments:
        order_id:
          exception:
            title: Tutti
