label: Profili
display:
  default:
    display_title: Principale
    display_options:
      exposed_form:
        options:
          submit_button: Applica
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_desc_label: Disc
      arguments:
        uid:
          exception:
            title: Tutti
        type:
          exception:
            title: Tutti
        status:
          exception:
            title: Tutti
      title: Profili
