label: Archivio
description: 'Tutti i contenuti, per mese.'
display:
  default:
    display_title: Principale
    display_options:
      title: 'Archivio mensile'
      exposed_form:
        options:
          submit_button: Applica
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_desc_label: Disc
      pager:
        options:
          expose:
            items_per_page_label: 'Voci per pagina'
            items_per_page_options_all_label: '- Tutto -'
            offset_label: Scostamento
  block_1:
    display_title: Blocco
  page_1:
    display_title: Pagina
