features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://avel-logo.png'
favicon:
  use_default: 0
  path: 'public://avel.png'
  mimetype: image/png
navbar_position: 0
header_container: 1
content_container: 1
footer_container: 1
content_front_container: 0
content_product_container: 1
header_class: ''
footer_class: ''
