definitions:
  contact__site_page:
    weight: -48
    menu_name: footer-right
    parent: ''
    enabled: true
    expanded: false
  standard__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
    weight: -50
  user__page:
    enabled: true
    menu_name: account
    parent: ''
    expanded: false
    weight: -10
  user__logout:
    enabled: true
    menu_name: account
    parent: ''
    expanded: false
    weight: -50
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__catalog_of_variations__42':
    weight: -50
    menu_name: main
    parent: 'menu_link_content:15ac1c66-fac2-4e0a-876d-831bb764ccd9'
    enabled: true
    expanded: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__catalog_of_variations__43':
    weight: -49
    menu_name: main
    parent: 'menu_link_content:15ac1c66-fac2-4e0a-876d-831bb764ccd9'
    expanded: true
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__catalog_of_variations__44':
    weight: -48
    menu_name: main
    parent: 'menu_link_content:15ac1c66-fac2-4e0a-876d-831bb764ccd9'
    expanded: true
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__catalog_of_variations__45':
    weight: -47
    menu_name: main
    parent: 'menu_link_content:15ac1c66-fac2-4e0a-876d-831bb764ccd9'
    expanded: true
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__catalog_of_variations__48':
    weight: -46
    menu_name: main
    parent: 'menu_link_content:15ac1c66-fac2-4e0a-876d-831bb764ccd9'
    expanded: true
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
langcode: ru
