module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  advagg: 0
  advagg_bundler: 0
  advagg_css_minify: 0
  advagg_js_minify: 0
  ajax_add_to_cart: 0
  allowed_formats: 0
  antibot: 0
  automated_cron: 0
  avis_catalog_aliases: 0
  avis_flag_cleaner: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_class: 0
  block_content: 0
  block_type_templates: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  color_field: 0
  colorbox: 0
  comment: 0
  commerce: 0
  commerce_cart: 0
  commerce_checkout: 0
  commerce_checkout_geo_restriction: 0
  commerce_number_pattern: 0
  commerce_order: 0
  commerce_pado: 0
  commerce_payment: 0
  commerce_payment_example: 0
  commerce_paypal: 0
  commerce_price: 0
  commerce_product: 0
  commerce_store: 0
  commerce_variation_cart_form: 0
  config: 0
  config_translation: 0
  consumer_image_styles: 0
  consumers: 0
  contact: 0
  contact_poup: 0
  contact_storage: 0
  context: 0
  context_ui: 0
  contextual: 0
  critical_css: 0
  ctools: 0
  datetime: 0
  dblog: 0
  device_geolocation: 0
  ds: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  eck: 0
  editor: 0
  embed: 0
  entity: 0
  entity_embed: 0
  entity_reference_revisions: 0
  facets: 0
  facets_pretty_paths: 0
  facets_range_widget: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  filter: 0
  fitvids: 0
  flag: 0
  flag_bookmark: 0
  flag_follower: 0
  fontawesome: 0
  fz152: 0
  fz152_contact: 0
  geolocation: 0
  geolocation_yandex: 0
  google_tag: 0
  help: 0
  history: 0
  honeypot: 0
  hook_post_action: 0
  icon_select: 0
  image: 0
  image_captcha: 0
  image_effects: 0
  imageapi_optimize: 0
  imageapi_optimize_webp: 0
  imageapi_optimize_webp_responsive: 0
  imagemagick: 0
  infobusiness: 0
  inline_entity_form: 0
  jsonapi: 0
  kint: 0
  language: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  locale: 0
  mailsystem: 0
  menu_block: 0
  menu_link_attributes: 0
  menu_per_role: 0
  menu_ui: 0
  metatag: 0
  metatag_hreflang: 0
  metatag_open_graph: 0
  metatag_views: 0
  module_filter: 0
  n1: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_admin: 0
  paragraphs_viewmode: 0
  path: 0
  path_alias: 0
  profile: 0
  rdf: 0
  recaptcha: 0
  recently_read: 0
  redirect: 0
  redirect_404: 0
  replicate: 0
  request_data_conditions: 0
  responsive_image: 0
  rest: 0
  restui: 0
  scantukan: 0
  search_api: 0
  search_api_db: 0
  search_api_db_defaults: 0
  serialization: 0
  share_everywhere: 0
  shortcut: 0
  simple_sitemap: 0
  slick: 0
  slick_paragraphs: 0
  slick_ui: 0
  slick_views: 0
  smart_ip: 0
  smart_ip_maxmind_geoip2_bin_db: 0
  smtp: 0
  state_machine: 0
  statistics: 0
  structure_sync: 0
  styleguide: 0
  superfish: 0
  swiftmailer: 0
  system: 0
  tablefield: 0
  taxonomy: 0
  taxonomy_menu: 0
  terms_agreement: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  tvi: 0
  update: 0
  user: 0
  video_embed_field: 0
  view_mode_page: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_flipped_table: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  context_metadata: 1000
  minimal: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  n1_commerce: 0
  aviselectronics: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: ru
