selectors: ".node\r\n.paragraph--type--gallery-video div\r\n.fluid-width-video-wrapper\r\n.paragraph--type--video .field__item"
custom_vendors: ''
ignore_selectors: ''
_core:
  default_config_hash: 2VIFfYIzLIphEpkJSH9KfhEE0P66ieHfusDj6QMJIzY
langcode: ru
