session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    '': null
    en: en
    ru: ru
    es: es
    pt-pt: pt-pt
    it: it
    zh-hant: zh-hant
  domains:
    en: ''
    ru: ''
    es: ''
    pt-pt: ''
    it: ''
    zh-hant: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
langcode: ru
