smtp_on: false
smtp_host: smtp.yandex.ru
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: sales@aviselectronics.com
smtp_password: Avel0930!
smtp_from: sales@aviselectronics.com
smtp_fromname: ''
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
smtp_timeout: 30
smtp_keepalive: false
smtp_autotls: true
