tips:
  search-api-index-form-name:
    label: 'Имя индекса'
  search-api-index-form-tracker:
    label: Изменения
  search-api-index-form-server:
    label: Servidor
  search-api-index-form-options:
    label: 'Definições avançadas'
