label: 'Adicionar idiomas'
tips:
  language-add-overview:
    label: 'Adicionar idiomas'
    body: '<p>Эта страница предоставляет возможность добавить на сайт общеизвестные языки.</p><p>Если необходимый язык отсутствует, можно добавить собственный язык.</p>'
  language-add-choose:
    label: 'Selecionar o idioma'
    body: '<p>Выберите язык из списка, или выберите пункт "Собственный язык...", который находится в конце списка.</p><p>После выбора языка, нажмите кнопку "Добавить язык" .</p><p>При добавлении собственного языка, появится дополнительная форма, где будет необходимо ввести название, код и направление языка.</p>'
  language-add-continue:
    label: Продолжение
