tips:
  search-api-index-fields-label:
    label: Etiqueta
  search-api-index-fields-machine-name:
    label: 'Nome de máquina'
  search-api-index-fields-type:
    label: Tipo
  search-api-index-fields-edit:
    label: 'Editar campo'
  search-api-index-fields-remove:
    label: 'Remover campo'
  search-api-index-fields-submit:
    label: 'Guardar alterações'
