label: 'Procurar conteúdos'
display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          submit_button: Pesquisar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          tags:
            previous: '‹ anterior'
            next: 'seguinte ›'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      filters:
        search_api_fulltext:
          expose:
            label: Pesquisar
  page_1:
    display_title: Página
