display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
          tags:
            previous: '‹ anterior'
            next: 'seguinte ›'
            first: '« primeira'
            last: 'última »'
      fields:
        commerce_order_bulk_form:
          action_title: 'Com a seleção'
        type:
          label: Tipo
        store_id:
          label: Loja
        uid:
          label: Cliente
        changed:
          label: Atualizado
        operations:
          label: Operações
      filters:
        type:
          expose:
            label: Tipo
  page_1:
    display_title: Página
