label: Ficheiro
description: 'Todo o conteúdo, por mês.'
display:
  default:
    display_title: Principal
    display_options:
      title: 'Arquivo mensal'
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
  block_1:
    display_title: Bloco
  page_1:
    display_title: Página
