display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      fields:
        uid:
          label: 'Criado por'
        created:
          label: 'Criado em'
        parent_id:
          label: Pai
        status:
          label: Publicado
        type:
          label: Tipo
        nothing:
          label: Ação
          alter:
            text: eliminar
            alt: eliminar
      filters:
        type:
          expose:
            label: Tipo
