display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          tags:
            previous: '‹ Anterior'
            next: 'Siguiente >'
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        order_number:
          label: 'Número de pedido'
        placed:
          label: Fecha
        state:
          label: Estado
      title: Pedidos
      arguments:
        uid:
          exception:
            title: Todo(s)
  order_page:
    display_options:
      menu:
        title: Pedidos
