label: Tiendas
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
          tags:
            previous: '‹ anterior'
            next: 'siguiente ›'
            first: '« primero'
            last: 'última »'
      fields:
        commerce_store_bulk_form:
          action_title: 'Con selección'
        name:
          label: Nombre
        type:
          label: Tipo
        operations:
          label: Operaciones
      filters:
        type:
          expose:
            label: Tipo
      title: Tiendas
  page_1:
    display_title: Página
