label: Perfiles
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      arguments:
        uid:
          exception:
            title: Todo(s)
        type:
          exception:
            title: Todo(s)
        status:
          exception:
            title: Todo(s)
      title: Perfiles
