settings:
  default_submit_button_label: Enviar
  default_reset_button_label: Restablecer
  default_wizard_prev_button_label: '< Anterior'
  default_wizard_start_label: Comienzo
  default_wizard_confirmation_label: Completo
  default_preview_next_button_label: 'Vista previa'
  default_preview_prev_button_label: '< Anterior'
  default_preview_label: 'Vista previa'
  default_draft_button_label: 'Guardar borrador'
  default_draft_saved_message: 'Envío guardado. Usted puede volver a este formuario luego y recuperará sus valores actuales.'
element:
  default_more_title: Más
test:
  names: "first_name:\n  - John\n  - Paul\n  - Ringo\n  - George\nlast_name:\n  - Lennon\n  - McCartney\n  - Starr\n  - Harrison\naddress:\n  - '10 Main Street'\n  - '11 Brook Alley Road. APT 1'\nzip:\n  - '11111'\n  - '12345'\n  - 12345-6789\nphone:\n  - 123-456-7890\n  - 098-765-4321\nfax:\n  - 123-456-7890\n  - 098-765-4321\ncity:\n  - Springfield\n  - Pleasantville\n  - 'Hill Valley'\nurl:\n  - 'http://example.com'\n  - 'http://test.com'\ndefault:\n  - Loremipsum\n  - Oratione\n  - Dixisset\npostal_code:\n  - '11111'\n  - '12345'\n  - 12345-6789"
