label: 語言
tips:
  language-overview:
    label: 語言
    body: '<p>Страница "Языки" позволяет вам добавлять, редактировать, удалять, и упорядочивать языки для сайта.</p>'
  language-add:
    label: 新增語言
    body: '<p>Для добавления языков на ваш сайт, нажмите кнопку "Добавить язык".</p><p>Добавленные языки будут отображаться в списке языков и потом могут быть отредактированы или удалены.</p>'
  language-reorder:
    label: 重新排序語言
    body: '<p>Чтобы изменить порядок языков на сайте, используйте иконки перемещения рядом с каждым языком.</p><p>В указанной здесь последовательности языки будут отображаться в списках языков на сайте, например в блоках переключения языков, которые предоставляются модулями Перевод Интерфейса и Перевод Материалов.</p><p>После окончания изменения порядка языков, нажмите на кнопку "Сохранить конфигурацию" чтобы изменения вступили в силу.</p>'
  language-default:
    label: 設定為預設語言
    body: '<p>Вы можете выбрать язык сайта по умолчанию, выбрав один из настроенных языков языком по умолчанию. Сайт будет использовать язык по умолчанию в ситуациях, когда выбор не сделан, но язык должен быть установлен, например язык отображаемого интерфейса.</p>'
  language-operations:
    label: 修改語言
    body: '<p>Операции предназначенные для редактирования и удаления ваших языков.</p><p>Вы можете отредактировать имя и направление языка.</p><p>Удалённые языки можно вернуть обратно позже. Удаление языка удалит все переводы интерфейса связанные с ним, и для всех материалов на этом языке будет установлен нейтральный язык. Обратите внимание, что вы не можете удалить язык установленный по умолчанию для сайта.</p>'
  language-continue:
    label: 繼續
