label: 'Страница редактирования представления'
tips:
  views-main:
    label: 'Управление настройками представления'
    body: 'Просмотр или редактирование конфигурации.'
  views-ui-displays:
    label: 'Отображения в этом представлении'
    body: 'Отображение - это способ вывода результатов, например, в виде страницы или блока. Представление может содержать несколько отображений, которые перечислены здесь. Активное отображение подсвечено.'
  views-ui-view-admin:
    label: 'View 管理'
    body: 'Выполнение административных задач, включающие добавление описания и создание копии. Нажмите раскрывающуюся кнопку для просмотра доступных действий.'
  views-ui-format:
    label: 輸出格式
  views-ui-fields:
    label: 欄位
    body: 'Если это представление использует поля, они будут перечислены здесь. Нажмите на поле для того, чтобы настроить его.'
  views-ui-filter:
    label: 'Фильтрация представления'
    body: 'Добавьте фильтры для ограничения вывода результатов. Например, для отображения только <em>опубликованных</em> материалов, необходимо добавить фильтр <em>Опубликовано</em> и выбрать <em>Да</em>'
  views-ui-filter-operations:
    label: 篩選
    body: 新增、重排或移除過濾條件。
  views-ui-sorts:
    label: 排序的標準
    body: 'Управляйте порядком вывода результатов. Нажмите на активное правило сортировки для его настройки.'
  views-ui-sorts-operations:
    label: 排序動作
    body: 新增、重排或移除規則。
  views-ui-preview:
    label: 預覽
    body: 'Показать предварительный просмотр вывода представления.'
