label: 編輯語言
tips:
  language-edit-overview:
    label: 編輯語言
    body: '<p>Эта страница предоставляет возможность редактировать язык на вашем сайте, включая собственные языки.</p>'
  language-edit-langcode:
    label: 語言代碼
    body: '<p>Невозможно изменить код языка сайта, так как он используется системой для отслеживания языка.</p>'
  language-edit-label:
    label: 語言名稱
    body: 'Название языка используется по всему сайту для всех пользователей и пишется на английском языке. Названия встроенных языков могут быть переведены с помощью модуля Interface Translation, а названия встроенных и собственных языков могут быть переведены с помощью модуля Configuration Translation.'
  language-edit-direction:
    label: 語言方向
    body: '<p>Выберите направление языка - "Слева-направо" или "Справа-налево".</p><p>Обратите внимание, что не все темы поддерживают направление "Справа-налево", поэтому проверьте свою тему перед использованием направления "Справа-налево".</p>'
  language-edit-continue:
    label: 繼續
