label: 翻譯
tips:
  locale-overview:
    label: 使用者介面翻譯
    body: 'На данной странице вы можете перевести пользовательский интерфейс или изменить существующий перевод. Если вы изначально установили сайт на Английском, перед началом использования этой страницы, вам необходимо добавить другой язык на странице <a href="[site:url]admin/config/regional/language">Языки</a>.'
  locale-language:
    label: 翻譯語言
    body: 選擇您要翻譯的語言。
  locale-search:
    label: 搜尋
    body: 'Введите опредёленное слово или предложение, которое необходимо перевести. Можно ввести только часть слова.'
  locale-filter:
    label: 篩選搜尋
    body: 'Вы можете искать непереведённые строки, если вы хотите перевести что-нибудь ещё непереведённое. Если вы хотите изменить существующий перевод, вы можете искать только переведённые строки.'
  locale-submit:
    label: 套用您的搜尋條件
    body: 'Для применения выбранного критерия поиска, нажмите кнопку <em>Фильтр</em>.'
  locale-translate:
    label: 翻譯
    body: 'Вы можете написать свой собственный вариант перевода в текстовых полях правой колонки. Попробуйте выяснить, в каком контексте будет использоваться текст для того, чтобы перевести его как можно точнее.'
  locale-validate:
    label: 驗證此翻譯
    body: 'После завершения ваших переводов нажмите кнопку <em>Сохранить переводы</em>. Необходимо сохранять переводы каждый раз перед изменением страницы или выполнением нового поиска.'
  locale-continue:
    label: 繼續
    body: 'Выполненные здесь переводы будут использоваться в пользовательском интерфейсе сайта. Если их необходимо использовать на другом сайте или отредактировать во внешнем редакторе переводов, <a href="[site:url]admin/config/regional/translate/export">экспортируйте их</a> в po-файл, а затем <a href="[site:url]admin/config/regional/translate/import">импортируйте их</a>.'
