tips:
  search-api-index-form-name:
    label: 'Имя индекса'
  search-api-index-form-tracker:
    label: 過往文章
  search-api-index-form-server:
    label: Сервер
  search-api-index-form-options:
    label: 進階選項
