display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 套用
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      fields:
        purchased_entity:
          label: 項目
        unit_price__number:
          label: 價格
        edit_quantity:
          label: 數量
        remove_button:
          label: 移除
        total_price__number:
          label: 總計
      arguments:
        order_id:
          exception:
            title: 所有
