label: 設定檔
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 套用
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      arguments:
        uid:
          exception:
            title: 所有
        type:
          exception:
            title: 所有
        status:
          exception:
            title: 所有
      title: 設定檔
