label: 商品
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 篩選
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      pager:
        options:
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
          tags:
            previous: '‹ 上一頁'
            next: '下一頁 ›'
            first: '« 第一頁'
            last: '最後一頁 »'
      fields:
        commerce_product_bulk_form:
          action_title: 對所選的內容執行…
        title:
          label: 標題
        type:
          label: 類型
        status:
          label: 狀態
          settings:
            format_custom_true: 已發表
            format_custom_false: 尚未發佈
        changed:
          label: 已更新
        operations:
          label: 操作
      filters:
        type:
          expose:
            label: 類型
        title:
          expose:
            label: 標題
      title: 商品
  page_1:
    display_title: 頁面
