label: Перевод
tips:
  locale-overview:
    label: 'Перевод пользовательского интерфейса'
    body: 'На данной странице вы можете перевести пользовательский интерфейс или изменить существующий перевод. Если вы изначально установили сайт на Английском, перед началом использования этой страницы, вам необходимо добавить другой язык на странице <a href="[site:url]admin/config/regional/language">Языки</a>.'
  locale-language:
    label: 'Язык перевода'
    body: 'Выберите язык, который вы хотите перевести.'
  locale-search:
    label: Поиск
    body: 'Введите опредёленное слово или предложение, которое необходимо перевести. Можно ввести только часть слова.'
