label: Содержимое
description: 'Поиск материалов и управление ими'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Фильтр
          reset_button_label: Сбросить
          exposed_sorts_label: 'Сортировать по'
          sort_asc_label: 'По возрастанию'
          sort_desc_label: 'По убыванию'
      pager:
        options:
          tags:
            previous: '‹ Предыдущий'
            next: 'Следующий ›'
      filters:
        langcode:
          expose:
            label: Язык
      title: Содержимое
      empty:
        area_text_custom:
          content: 'Нет доступных материалов.'
    display_title: Основной
  page_1:
    display_options:
      menu:
        title: Содержимое
      tab_options:
        title: Содержимое
