settings:
  default_submit_button_label: Отправить
  default_reset_button_label: Reset
  default_wizard_start_label: Начало
  default_wizard_confirmation_label: Завершен
  default_preview_next_button_label: Предпросмотр
  default_preview_label: Предпросмотр
  default_draft_button_label: 'Сохранить черновик'
element:
  default_more_title: More
