css:
  brotli: true
  combine_media: false
  fix_type: true
dns_prefetch: false
path:
  convert:
    absolute_to_protocol_relative: true
    absolute: false
    force_https: false
cache_level: 2
cron_frequency: 86400
enabled: false
global_counter: 0
immutable: true
js:
  brotli: true
  fix_type: true
  preserve_external: null
skip_enabled_preprocess_check: false
show_bypass_cookie_message: true
symlinks: false
symlinksifownermatch: false
_core:
  default_config_hash: n6C9zqRMX-qIfun4IyStiMh1GvOi4H2ywSaNLBBdNBQ
langcode: ru
