site_key: 6Lf4qCoUAAAAAINvotLC4uH3ZGh8IXWFRU5qL4Hd
secret_key: 6Lf4qCoUAAAAAAGgZyBIBI7n9iTdAYhuDTfzN44f
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: true
_core:
  default_config_hash: ZKQ03ePk4sH2zESRw4tdZYw__nG2YN4Ru5roPL23g3A
langcode: ru
