auth:
  social_auth_vk:
    route: social_auth_vk.redirect_to_vk
    img_path: modules/social_auth_vk/img/vk_logo.svg
post_login: /user
redirect_user_form: false
disable_admin_login: true
disabled_roles:
  administrator: '0'
_core:
  default_config_hash: 1tS3jCuYxV3TXQ2cq320XarjdXWprvWK5bru8DCsIUY
langcode: ru
